# Generated by Django 5.2.8 on 2025-11-15 13:06
# Edited to safely migrate existing data

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_make_category_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Author's full name", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Author biography or description')),
                ('photo', models.ImageField(blank=True, help_text='Author photo/avatar', null=True, upload_to='authors/')),
                ('contact_info', models.TextField(blank=True, help_text='Contact information (optional)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Add temporary nullable field for author migration
        migrations.AddField(
            model_name='article',
            name='author_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='articles_new',
                to='articles.author'
            ),
        ),
    ]
