# Generated by Django 5.2.8 on 2025-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text="Page title (e.g., 'About Us')", max_length=200)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'about-us')", max_length=200, unique=True)),
                ('content', models.TextField(help_text='Page content (plain text for now, rich text editor optional for future)')),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['title'],
            },
        ),
    ]
